import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#3a4a5f',
        'inverse-on-surface': '#283044',
        'on-primary-container': '#c1deff',
        'on-tertiary-container': '#d6d8ff',
        'outline-variant': '#424752',
        'surface-container-lowest': '#060e20',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed-variant': '#38485d',
        'inverse-surface': '#dae2fd',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#4a55bd',
        'on-background': '#dae2fd',
        'surface': '#0b1326',
        'inverse-primary': '#00629d',
        'surface-variant': '#2d3449',
        'tertiary-fixed-dim': '#bdc2ff',
        'on-surface-variant': '#c2c6d4',
        'error-container': '#93000a',
        'on-tertiary': '#131e8c',
        'outline': '#8c919d',
        'on-primary-fixed-variant': '#004a77',
        'on-secondary': '#213145',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3d',
        'error': '#ffb4ab',
        'on-primary-fixed': '#001d33',
        'primary-fixed-dim': '#98cbff',
        'on-tertiary-fixed-variant': '#2f3aa3',
        'secondary-fixed': '#d3e4fe',
        'surface-tint': '#98cbff',
        'on-primary': '#003354',
        'on-error': '#690005',
        'on-secondary-fixed': '#0b1c30',
        'surface-container-highest': '#2d3449',
        'surface-container': '#171f33',
        'primary-container': '#00649f',
        'primary-fixed': '#cfe5ff',
        'background': '#0b1326',
        'secondary': '#b7c8e1',
        'on-surface': '#dae2fd',
        'tertiary': '#bdc2ff',
        'surface-dim': '#0b1326',
        'primary': '#98cbff',
        'on-tertiary-fixed': '#000767',
        'tertiary-fixed': '#e0e0ff',
        'surface-bright': '#31394d',
        'on-secondary-container': '#a9bad3',
        // Light mode equivalents
        'light-surface': '#f8f9ff',
        'light-surface-container': '#eef0fa',
        'light-surface-container-low': '#f4f5ff',
        'light-surface-container-high': '#e2e4f0',
        'light-on-surface': '#181c2e',
        'light-on-surface-variant': '#44474f',
        'light-primary': '#00629d',
        'light-on-primary': '#ffffff',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.375rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
        'slide-right': {
          '0%': { transform: 'scaleX(0)', transformOrigin: 'left' },
          '100%': { transform: 'scaleX(1)', transformOrigin: 'left' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.7s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fade-in 0.5s ease forwards',
        'pulse-slow': 'pulse-slow 3s ease-in-out infinite',
        'slide-right': 'slide-right 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
}
export default config
